Repository insightsengineering/teal.goshawk, pull requests merged in 2022-07, with the labels that each got.

#166 DESC and README
  DESCRIPTION
  README.md
Labels: core

#170 type coercion warning
  NEWS.md
  R/utils.R
Labels: core

#172 Add option to control starting value of relative plot height slider
  NEWS.md
  R/tm_g_gh_lineplot.R
  man/tm_g_gh_lineplot.Rd
Labels: core

#171 161 Implement `nestcolor` in `teal.goshawk`
  DESCRIPTION
  NEWS.md
  R/tm_g_gh_boxplot.R
  R/tm_g_gh_lineplot.R
  man/tm_g_gh_boxplot.Rd
  man/tm_g_gh_lineplot.Rd
  staged_dependencies.yaml
Labels: core, sme

#176 Update font awesome icon labels for FA 6
  R/tm_g_gh_lineplot.R
Labels: refactor

#174 remove _FILTERED
  NEWS.md
  R/tm_g_gh_correlationplot.R
  R/utils.R
Labels: core

#175 reporter_cleaning
  R/tm_g_gh_boxplot.R
  R/tm_g_gh_correlationplot.R
  R/tm_g_gh_density_distribution_plot.R
  R/tm_g_gh_lineplot.R
  R/tm_g_gh_scatterplot.R
  R/tm_g_gh_spaghettiplot.R
Labels: core

#178 review css
  R/tm_g_gh_lineplot.R
  R/tm_g_gh_spaghettiplot.R
  R/toggleable_slider.R
  R/utils.R
  inst/css/custom.css
  man/include_css_files.Rd
Labels: core
